# Generated by Django 4.1.2 on 2023-05-10 16:33

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_profile_bio"),
    ]

    operations = [
        migrations.CreateModel(
            name="tutorial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tutorial_Title", models.CharField(max_length=200)),
                ("tutorial_Body", models.TextField()),
                ("tutorial_Video", embed_video.fields.EmbedVideoField()),
            ],
            options={
                "verbose_name_plural": "Tutorial",
            },
        ),
    ]
