# Generated by Django 4.1.2 on 2023-05-26 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_tutorial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="tutorial",
        ),
    ]
